-- AlterTable
ALTER TABLE `arrivalstatuses` ADD COLUMN `statusApproval` VARCHAR(191) NULL DEFAULT 'MENUNGGUPERSETUJUAN',
    MODIFY `status` VARCHAR(191) NOT NULL DEFAULT 'MENUNGGUQC/TIMBANG',
    MODIFY `statusQc` VARCHAR(191) NULL DEFAULT 'MENUNGGUQC',
    MODIFY `statusWeighing` VARCHAR(191) NULL DEFAULT 'MENUNGGUTIMBANG';
