export const ArrivalStatus = {
  WAITING_ARRIVAL: "MENUNGGUQC/TIMBANG",
  QC_PENDING: "MENUNGGUQC",
  QC_COMPLETED: "SELESAIQC",
  WEIGHING_COMPLETED: "SELESAITIMBANG",
  WEIGHING_PENDING: "MENUNGGUTIMBANG",
  APPROVAL_PENDING: "MENUNGGUPERSETUJUAN",
  APPROVAL_COMPLETED: "DISETUJUI",
  REJECTED: "DITOLAK",
} as const;

export type ArrivalStatus = typeof ArrivalStatus[keyof typeof ArrivalStatus];